// Code generated by protoc-gen-go. DO NOT EDIT.
// source: iot-openevse-service.proto

/*
Package iot_openevse_service is a generated protocol buffer package.

It is generated from these files:
	iot-openevse-service.proto

It has these top-level messages:
	GetRequest
	GetAmmeterSettingsResponse
	GetAuthLockStateResponse
	GetChargeLimitResponse
	GetCurrentCapacityRangeInAmpsResponse
	GetDelayTimerResponse
	GetEnergyUsageResponse
	GetEvConnectStateResponse
	GetFaultCountersResponse
	GetOverTemperatureThresholdsResponse
	GetRtcTimeResponse
	GetSettingsResponse
	GetTimeLimitResponse
	GetVersionResponse
	GetVoltmeterSettingsResponse
	SetResponse
	SetRtcTimeRequest
*/
package iot_openevse_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EvConnectState int32

const (
	EvConnectState_NOT_CONNECTED EvConnectState = 0
	EvConnectState_CONNECTED     EvConnectState = 1
	EvConnectState_UNKNOWN       EvConnectState = 2
)

var EvConnectState_name = map[int32]string{
	0: "NOT_CONNECTED",
	1: "CONNECTED",
	2: "UNKNOWN",
}
var EvConnectState_value = map[string]int32{
	"NOT_CONNECTED": 0,
	"CONNECTED":     1,
	"UNKNOWN":       2,
}

func (x EvConnectState) String() string {
	return proto.EnumName(EvConnectState_name, int32(x))
}
func (EvConnectState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetRequest struct {
	Host string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type GetAmmeterSettingsResponse struct {
	CurrentScaleFactor int32 `protobuf:"varint,1,opt,name=currentScaleFactor" json:"currentScaleFactor,omitempty"`
	CurrentOffset      int32 `protobuf:"varint,2,opt,name=currentOffset" json:"currentOffset,omitempty"`
}

func (m *GetAmmeterSettingsResponse) Reset()                    { *m = GetAmmeterSettingsResponse{} }
func (m *GetAmmeterSettingsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAmmeterSettingsResponse) ProtoMessage()               {}
func (*GetAmmeterSettingsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetAmmeterSettingsResponse) GetCurrentScaleFactor() int32 {
	if m != nil {
		return m.CurrentScaleFactor
	}
	return 0
}

func (m *GetAmmeterSettingsResponse) GetCurrentOffset() int32 {
	if m != nil {
		return m.CurrentOffset
	}
	return 0
}

type GetAuthLockStateResponse struct {
	Locked bool `protobuf:"varint,1,opt,name=locked" json:"locked,omitempty"`
}

func (m *GetAuthLockStateResponse) Reset()                    { *m = GetAuthLockStateResponse{} }
func (m *GetAuthLockStateResponse) String() string            { return proto.CompactTextString(m) }
func (*GetAuthLockStateResponse) ProtoMessage()               {}
func (*GetAuthLockStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetAuthLockStateResponse) GetLocked() bool {
	if m != nil {
		return m.Locked
	}
	return false
}

type GetChargeLimitResponse struct {
	MilliAmps  int32 `protobuf:"varint,1,opt,name=milliAmps" json:"milliAmps,omitempty"`
	MilliVolts int32 `protobuf:"varint,2,opt,name=milliVolts" json:"milliVolts,omitempty"`
}

func (m *GetChargeLimitResponse) Reset()                    { *m = GetChargeLimitResponse{} }
func (m *GetChargeLimitResponse) String() string            { return proto.CompactTextString(m) }
func (*GetChargeLimitResponse) ProtoMessage()               {}
func (*GetChargeLimitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetChargeLimitResponse) GetMilliAmps() int32 {
	if m != nil {
		return m.MilliAmps
	}
	return 0
}

func (m *GetChargeLimitResponse) GetMilliVolts() int32 {
	if m != nil {
		return m.MilliVolts
	}
	return 0
}

type GetCurrentCapacityRangeInAmpsResponse struct {
	MinAmps int32 `protobuf:"varint,1,opt,name=minAmps" json:"minAmps,omitempty"`
	MaxAmps int32 `protobuf:"varint,2,opt,name=maxAmps" json:"maxAmps,omitempty"`
}

func (m *GetCurrentCapacityRangeInAmpsResponse) Reset()         { *m = GetCurrentCapacityRangeInAmpsResponse{} }
func (m *GetCurrentCapacityRangeInAmpsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCurrentCapacityRangeInAmpsResponse) ProtoMessage()    {}
func (*GetCurrentCapacityRangeInAmpsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4}
}

func (m *GetCurrentCapacityRangeInAmpsResponse) GetMinAmps() int32 {
	if m != nil {
		return m.MinAmps
	}
	return 0
}

func (m *GetCurrentCapacityRangeInAmpsResponse) GetMaxAmps() int32 {
	if m != nil {
		return m.MaxAmps
	}
	return 0
}

type GetDelayTimerResponse struct {
	StartTime string `protobuf:"bytes,1,opt,name=startTime" json:"startTime,omitempty"`
	EndTime   string `protobuf:"bytes,2,opt,name=endTime" json:"endTime,omitempty"`
}

func (m *GetDelayTimerResponse) Reset()                    { *m = GetDelayTimerResponse{} }
func (m *GetDelayTimerResponse) String() string            { return proto.CompactTextString(m) }
func (*GetDelayTimerResponse) ProtoMessage()               {}
func (*GetDelayTimerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetDelayTimerResponse) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *GetDelayTimerResponse) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type GetEnergyUsageResponse struct {
	WhInSession   int32 `protobuf:"varint,1,opt,name=whInSession" json:"whInSession,omitempty"`
	WhAccumulated int32 `protobuf:"varint,2,opt,name=whAccumulated" json:"whAccumulated,omitempty"`
}

func (m *GetEnergyUsageResponse) Reset()                    { *m = GetEnergyUsageResponse{} }
func (m *GetEnergyUsageResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEnergyUsageResponse) ProtoMessage()               {}
func (*GetEnergyUsageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetEnergyUsageResponse) GetWhInSession() int32 {
	if m != nil {
		return m.WhInSession
	}
	return 0
}

func (m *GetEnergyUsageResponse) GetWhAccumulated() int32 {
	if m != nil {
		return m.WhAccumulated
	}
	return 0
}

type GetEvConnectStateResponse struct {
	State EvConnectState `protobuf:"varint,1,opt,name=state,enum=iot_openevse_service.EvConnectState" json:"state,omitempty"`
}

func (m *GetEvConnectStateResponse) Reset()                    { *m = GetEvConnectStateResponse{} }
func (m *GetEvConnectStateResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEvConnectStateResponse) ProtoMessage()               {}
func (*GetEvConnectStateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetEvConnectStateResponse) GetState() EvConnectState {
	if m != nil {
		return m.State
	}
	return EvConnectState_NOT_CONNECTED
}

type GetFaultCountersResponse struct {
	Gfdi       int32 `protobuf:"varint,1,opt,name=gfdi" json:"gfdi,omitempty"`
	NoGround   int32 `protobuf:"varint,2,opt,name=noGround" json:"noGround,omitempty"`
	StuckRelay int32 `protobuf:"varint,3,opt,name=stuckRelay" json:"stuckRelay,omitempty"`
}

func (m *GetFaultCountersResponse) Reset()                    { *m = GetFaultCountersResponse{} }
func (m *GetFaultCountersResponse) String() string            { return proto.CompactTextString(m) }
func (*GetFaultCountersResponse) ProtoMessage()               {}
func (*GetFaultCountersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetFaultCountersResponse) GetGfdi() int32 {
	if m != nil {
		return m.Gfdi
	}
	return 0
}

func (m *GetFaultCountersResponse) GetNoGround() int32 {
	if m != nil {
		return m.NoGround
	}
	return 0
}

func (m *GetFaultCountersResponse) GetStuckRelay() int32 {
	if m != nil {
		return m.StuckRelay
	}
	return 0
}

type GetOverTemperatureThresholdsResponse struct {
	Ambient float32 `protobuf:"fixed32,1,opt,name=ambient" json:"ambient,omitempty"`
	Ir      float32 `protobuf:"fixed32,2,opt,name=ir" json:"ir,omitempty"`
}

func (m *GetOverTemperatureThresholdsResponse) Reset()         { *m = GetOverTemperatureThresholdsResponse{} }
func (m *GetOverTemperatureThresholdsResponse) String() string { return proto.CompactTextString(m) }
func (*GetOverTemperatureThresholdsResponse) ProtoMessage()    {}
func (*GetOverTemperatureThresholdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9}
}

func (m *GetOverTemperatureThresholdsResponse) GetAmbient() float32 {
	if m != nil {
		return m.Ambient
	}
	return 0
}

func (m *GetOverTemperatureThresholdsResponse) GetIr() float32 {
	if m != nil {
		return m.Ir
	}
	return 0
}

type GetRtcTimeResponse struct {
	RtcTime string `protobuf:"bytes,1,opt,name=rtcTime" json:"rtcTime,omitempty"`
}

func (m *GetRtcTimeResponse) Reset()                    { *m = GetRtcTimeResponse{} }
func (m *GetRtcTimeResponse) String() string            { return proto.CompactTextString(m) }
func (*GetRtcTimeResponse) ProtoMessage()               {}
func (*GetRtcTimeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetRtcTimeResponse) GetRtcTime() string {
	if m != nil {
		return m.RtcTime
	}
	return ""
}

type GetSettingsResponse struct {
	Amperes int32    `protobuf:"varint,1,opt,name=amperes" json:"amperes,omitempty"`
	Flags   []string `protobuf:"bytes,2,rep,name=flags" json:"flags,omitempty"`
}

func (m *GetSettingsResponse) Reset()                    { *m = GetSettingsResponse{} }
func (m *GetSettingsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetSettingsResponse) ProtoMessage()               {}
func (*GetSettingsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *GetSettingsResponse) GetAmperes() int32 {
	if m != nil {
		return m.Amperes
	}
	return 0
}

func (m *GetSettingsResponse) GetFlags() []string {
	if m != nil {
		return m.Flags
	}
	return nil
}

type GetTimeLimitResponse struct {
	Limit int32 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
}

func (m *GetTimeLimitResponse) Reset()                    { *m = GetTimeLimitResponse{} }
func (m *GetTimeLimitResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTimeLimitResponse) ProtoMessage()               {}
func (*GetTimeLimitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetTimeLimitResponse) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetVersionResponse struct {
	FirmwareVersion string `protobuf:"bytes,1,opt,name=firmwareVersion" json:"firmwareVersion,omitempty"`
	ProtocolVersion string `protobuf:"bytes,2,opt,name=protocolVersion" json:"protocolVersion,omitempty"`
}

func (m *GetVersionResponse) Reset()                    { *m = GetVersionResponse{} }
func (m *GetVersionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetVersionResponse) ProtoMessage()               {}
func (*GetVersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *GetVersionResponse) GetFirmwareVersion() string {
	if m != nil {
		return m.FirmwareVersion
	}
	return ""
}

func (m *GetVersionResponse) GetProtocolVersion() string {
	if m != nil {
		return m.ProtocolVersion
	}
	return ""
}

type GetVoltmeterSettingsResponse struct {
	Calefactor int32 `protobuf:"varint,1,opt,name=calefactor" json:"calefactor,omitempty"`
	Offset     int32 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
}

func (m *GetVoltmeterSettingsResponse) Reset()                    { *m = GetVoltmeterSettingsResponse{} }
func (m *GetVoltmeterSettingsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetVoltmeterSettingsResponse) ProtoMessage()               {}
func (*GetVoltmeterSettingsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *GetVoltmeterSettingsResponse) GetCalefactor() int32 {
	if m != nil {
		return m.Calefactor
	}
	return 0
}

func (m *GetVoltmeterSettingsResponse) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SetResponse struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *SetResponse) Reset()                    { *m = SetResponse{} }
func (m *SetResponse) String() string            { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()               {}
func (*SetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *SetResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type SetRtcTimeRequest struct {
	Host    string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	RtcTime string `protobuf:"bytes,2,opt,name=rtcTime" json:"rtcTime,omitempty"`
}

func (m *SetRtcTimeRequest) Reset()                    { *m = SetRtcTimeRequest{} }
func (m *SetRtcTimeRequest) String() string            { return proto.CompactTextString(m) }
func (*SetRtcTimeRequest) ProtoMessage()               {}
func (*SetRtcTimeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *SetRtcTimeRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *SetRtcTimeRequest) GetRtcTime() string {
	if m != nil {
		return m.RtcTime
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "iot_openevse_service.GetRequest")
	proto.RegisterType((*GetAmmeterSettingsResponse)(nil), "iot_openevse_service.GetAmmeterSettingsResponse")
	proto.RegisterType((*GetAuthLockStateResponse)(nil), "iot_openevse_service.GetAuthLockStateResponse")
	proto.RegisterType((*GetChargeLimitResponse)(nil), "iot_openevse_service.GetChargeLimitResponse")
	proto.RegisterType((*GetCurrentCapacityRangeInAmpsResponse)(nil), "iot_openevse_service.GetCurrentCapacityRangeInAmpsResponse")
	proto.RegisterType((*GetDelayTimerResponse)(nil), "iot_openevse_service.GetDelayTimerResponse")
	proto.RegisterType((*GetEnergyUsageResponse)(nil), "iot_openevse_service.GetEnergyUsageResponse")
	proto.RegisterType((*GetEvConnectStateResponse)(nil), "iot_openevse_service.GetEvConnectStateResponse")
	proto.RegisterType((*GetFaultCountersResponse)(nil), "iot_openevse_service.GetFaultCountersResponse")
	proto.RegisterType((*GetOverTemperatureThresholdsResponse)(nil), "iot_openevse_service.GetOverTemperatureThresholdsResponse")
	proto.RegisterType((*GetRtcTimeResponse)(nil), "iot_openevse_service.GetRtcTimeResponse")
	proto.RegisterType((*GetSettingsResponse)(nil), "iot_openevse_service.GetSettingsResponse")
	proto.RegisterType((*GetTimeLimitResponse)(nil), "iot_openevse_service.GetTimeLimitResponse")
	proto.RegisterType((*GetVersionResponse)(nil), "iot_openevse_service.GetVersionResponse")
	proto.RegisterType((*GetVoltmeterSettingsResponse)(nil), "iot_openevse_service.GetVoltmeterSettingsResponse")
	proto.RegisterType((*SetResponse)(nil), "iot_openevse_service.SetResponse")
	proto.RegisterType((*SetRtcTimeRequest)(nil), "iot_openevse_service.SetRtcTimeRequest")
	proto.RegisterEnum("iot_openevse_service.EvConnectState", EvConnectState_name, EvConnectState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Openevse service

type OpenevseClient interface {
	GetAmmeterSettings(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetAmmeterSettingsResponse, error)
	GetAuthLockState(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetAuthLockStateResponse, error)
	GetChargeLimit(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetChargeLimitResponse, error)
	GetCurrentCapacityRangeInAmps(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetCurrentCapacityRangeInAmpsResponse, error)
	GetDelayTimer(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetDelayTimerResponse, error)
	GetEnergyUsage(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetEnergyUsageResponse, error)
	GetEvConnectState(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetEvConnectStateResponse, error)
	GetFaultCounters(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetFaultCountersResponse, error)
	GetOverTemperatureThresholds(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetOverTemperatureThresholdsResponse, error)
	GetRtcTime(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetRtcTimeResponse, error)
	GetSettings(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetSettingsResponse, error)
	GetTimeLimit(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetTimeLimitResponse, error)
	GetVersion(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
	GetVoltmeterSettings(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetVoltmeterSettingsResponse, error)
	SetRtcTime(ctx context.Context, in *SetRtcTimeRequest, opts ...grpc.CallOption) (*SetResponse, error)
}

type openevseClient struct {
	cc *grpc.ClientConn
}

func NewOpenevseClient(cc *grpc.ClientConn) OpenevseClient {
	return &openevseClient{cc}
}

func (c *openevseClient) GetAmmeterSettings(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetAmmeterSettingsResponse, error) {
	out := new(GetAmmeterSettingsResponse)
	err := grpc.Invoke(ctx, "/iot_openevse_service.Openevse/GetAmmeterSettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openevseClient) GetAuthLockState(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetAuthLockStateResponse, error) {
	out := new(GetAuthLockStateResponse)
	err := grpc.Invoke(ctx, "/iot_openevse_service.Openevse/GetAuthLockState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openevseClient) GetChargeLimit(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetChargeLimitResponse, error) {
	out := new(GetChargeLimitResponse)
	err := grpc.Invoke(ctx, "/iot_openevse_service.Openevse/GetChargeLimit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openevseClient) GetCurrentCapacityRangeInAmps(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetCurrentCapacityRangeInAmpsResponse, error) {
	out := new(GetCurrentCapacityRangeInAmpsResponse)
	err := grpc.Invoke(ctx, "/iot_openevse_service.Openevse/GetCurrentCapacityRangeInAmps", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openevseClient) GetDelayTimer(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetDelayTimerResponse, error) {
	out := new(GetDelayTimerResponse)
	err := grpc.Invoke(ctx, "/iot_openevse_service.Openevse/GetDelayTimer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openevseClient) GetEnergyUsage(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetEnergyUsageResponse, error) {
	out := new(GetEnergyUsageResponse)
	err := grpc.Invoke(ctx, "/iot_openevse_service.Openevse/GetEnergyUsage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openevseClient) GetEvConnectState(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetEvConnectStateResponse, error) {
	out := new(GetEvConnectStateResponse)
	err := grpc.Invoke(ctx, "/iot_openevse_service.Openevse/GetEvConnectState", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openevseClient) GetFaultCounters(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetFaultCountersResponse, error) {
	out := new(GetFaultCountersResponse)
	err := grpc.Invoke(ctx, "/iot_openevse_service.Openevse/GetFaultCounters", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openevseClient) GetOverTemperatureThresholds(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetOverTemperatureThresholdsResponse, error) {
	out := new(GetOverTemperatureThresholdsResponse)
	err := grpc.Invoke(ctx, "/iot_openevse_service.Openevse/GetOverTemperatureThresholds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openevseClient) GetRtcTime(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetRtcTimeResponse, error) {
	out := new(GetRtcTimeResponse)
	err := grpc.Invoke(ctx, "/iot_openevse_service.Openevse/GetRtcTime", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openevseClient) GetSettings(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetSettingsResponse, error) {
	out := new(GetSettingsResponse)
	err := grpc.Invoke(ctx, "/iot_openevse_service.Openevse/GetSettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openevseClient) GetTimeLimit(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetTimeLimitResponse, error) {
	out := new(GetTimeLimitResponse)
	err := grpc.Invoke(ctx, "/iot_openevse_service.Openevse/GetTimeLimit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openevseClient) GetVersion(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	out := new(GetVersionResponse)
	err := grpc.Invoke(ctx, "/iot_openevse_service.Openevse/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openevseClient) GetVoltmeterSettings(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetVoltmeterSettingsResponse, error) {
	out := new(GetVoltmeterSettingsResponse)
	err := grpc.Invoke(ctx, "/iot_openevse_service.Openevse/GetVoltmeterSettings", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *openevseClient) SetRtcTime(ctx context.Context, in *SetRtcTimeRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := grpc.Invoke(ctx, "/iot_openevse_service.Openevse/SetRtcTime", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Openevse service

type OpenevseServer interface {
	GetAmmeterSettings(context.Context, *GetRequest) (*GetAmmeterSettingsResponse, error)
	GetAuthLockState(context.Context, *GetRequest) (*GetAuthLockStateResponse, error)
	GetChargeLimit(context.Context, *GetRequest) (*GetChargeLimitResponse, error)
	GetCurrentCapacityRangeInAmps(context.Context, *GetRequest) (*GetCurrentCapacityRangeInAmpsResponse, error)
	GetDelayTimer(context.Context, *GetRequest) (*GetDelayTimerResponse, error)
	GetEnergyUsage(context.Context, *GetRequest) (*GetEnergyUsageResponse, error)
	GetEvConnectState(context.Context, *GetRequest) (*GetEvConnectStateResponse, error)
	GetFaultCounters(context.Context, *GetRequest) (*GetFaultCountersResponse, error)
	GetOverTemperatureThresholds(context.Context, *GetRequest) (*GetOverTemperatureThresholdsResponse, error)
	GetRtcTime(context.Context, *GetRequest) (*GetRtcTimeResponse, error)
	GetSettings(context.Context, *GetRequest) (*GetSettingsResponse, error)
	GetTimeLimit(context.Context, *GetRequest) (*GetTimeLimitResponse, error)
	GetVersion(context.Context, *GetRequest) (*GetVersionResponse, error)
	GetVoltmeterSettings(context.Context, *GetRequest) (*GetVoltmeterSettingsResponse, error)
	SetRtcTime(context.Context, *SetRtcTimeRequest) (*SetResponse, error)
}

func RegisterOpenevseServer(s *grpc.Server, srv OpenevseServer) {
	s.RegisterService(&_Openevse_serviceDesc, srv)
}

func _Openevse_GetAmmeterSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenevseServer).GetAmmeterSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_openevse_service.Openevse/GetAmmeterSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenevseServer).GetAmmeterSettings(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openevse_GetAuthLockState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenevseServer).GetAuthLockState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_openevse_service.Openevse/GetAuthLockState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenevseServer).GetAuthLockState(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openevse_GetChargeLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenevseServer).GetChargeLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_openevse_service.Openevse/GetChargeLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenevseServer).GetChargeLimit(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openevse_GetCurrentCapacityRangeInAmps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenevseServer).GetCurrentCapacityRangeInAmps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_openevse_service.Openevse/GetCurrentCapacityRangeInAmps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenevseServer).GetCurrentCapacityRangeInAmps(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openevse_GetDelayTimer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenevseServer).GetDelayTimer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_openevse_service.Openevse/GetDelayTimer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenevseServer).GetDelayTimer(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openevse_GetEnergyUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenevseServer).GetEnergyUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_openevse_service.Openevse/GetEnergyUsage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenevseServer).GetEnergyUsage(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openevse_GetEvConnectState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenevseServer).GetEvConnectState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_openevse_service.Openevse/GetEvConnectState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenevseServer).GetEvConnectState(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openevse_GetFaultCounters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenevseServer).GetFaultCounters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_openevse_service.Openevse/GetFaultCounters",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenevseServer).GetFaultCounters(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openevse_GetOverTemperatureThresholds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenevseServer).GetOverTemperatureThresholds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_openevse_service.Openevse/GetOverTemperatureThresholds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenevseServer).GetOverTemperatureThresholds(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openevse_GetRtcTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenevseServer).GetRtcTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_openevse_service.Openevse/GetRtcTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenevseServer).GetRtcTime(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openevse_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenevseServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_openevse_service.Openevse/GetSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenevseServer).GetSettings(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openevse_GetTimeLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenevseServer).GetTimeLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_openevse_service.Openevse/GetTimeLimit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenevseServer).GetTimeLimit(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openevse_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenevseServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_openevse_service.Openevse/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenevseServer).GetVersion(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openevse_GetVoltmeterSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenevseServer).GetVoltmeterSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_openevse_service.Openevse/GetVoltmeterSettings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenevseServer).GetVoltmeterSettings(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Openevse_SetRtcTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRtcTimeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OpenevseServer).SetRtcTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/iot_openevse_service.Openevse/SetRtcTime",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OpenevseServer).SetRtcTime(ctx, req.(*SetRtcTimeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Openevse_serviceDesc = grpc.ServiceDesc{
	ServiceName: "iot_openevse_service.Openevse",
	HandlerType: (*OpenevseServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAmmeterSettings",
			Handler:    _Openevse_GetAmmeterSettings_Handler,
		},
		{
			MethodName: "GetAuthLockState",
			Handler:    _Openevse_GetAuthLockState_Handler,
		},
		{
			MethodName: "GetChargeLimit",
			Handler:    _Openevse_GetChargeLimit_Handler,
		},
		{
			MethodName: "GetCurrentCapacityRangeInAmps",
			Handler:    _Openevse_GetCurrentCapacityRangeInAmps_Handler,
		},
		{
			MethodName: "GetDelayTimer",
			Handler:    _Openevse_GetDelayTimer_Handler,
		},
		{
			MethodName: "GetEnergyUsage",
			Handler:    _Openevse_GetEnergyUsage_Handler,
		},
		{
			MethodName: "GetEvConnectState",
			Handler:    _Openevse_GetEvConnectState_Handler,
		},
		{
			MethodName: "GetFaultCounters",
			Handler:    _Openevse_GetFaultCounters_Handler,
		},
		{
			MethodName: "GetOverTemperatureThresholds",
			Handler:    _Openevse_GetOverTemperatureThresholds_Handler,
		},
		{
			MethodName: "GetRtcTime",
			Handler:    _Openevse_GetRtcTime_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _Openevse_GetSettings_Handler,
		},
		{
			MethodName: "GetTimeLimit",
			Handler:    _Openevse_GetTimeLimit_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _Openevse_GetVersion_Handler,
		},
		{
			MethodName: "GetVoltmeterSettings",
			Handler:    _Openevse_GetVoltmeterSettings_Handler,
		},
		{
			MethodName: "SetRtcTime",
			Handler:    _Openevse_SetRtcTime_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "iot-openevse-service.proto",
}

func init() { proto.RegisterFile("iot-openevse-service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 950 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xff, 0x6f, 0xdb, 0x44,
	0x14, 0xa7, 0xee, 0xba, 0xb5, 0xaf, 0x6b, 0x68, 0x8f, 0x32, 0x42, 0xb4, 0x4d, 0xc5, 0x2a, 0xa2,
	0x8c, 0x2d, 0xa0, 0xee, 0xb7, 0xf1, 0x03, 0xea, 0xb2, 0xce, 0xaa, 0x98, 0x92, 0xca, 0xc9, 0xba,
	0x09, 0x10, 0xdd, 0xcd, 0x79, 0x49, 0x4c, 0x6c, 0x5f, 0xb8, 0x3b, 0xa7, 0x54, 0x42, 0x88, 0xbf,
	0x85, 0xbf, 0x14, 0xdd, 0xf9, 0x1c, 0xdb, 0x89, 0xbd, 0x59, 0xea, 0x6f, 0x79, 0x5f, 0xfc, 0x3e,
	0xaf, 0xef, 0xbd, 0xfb, 0x7c, 0x0a, 0x2d, 0x9f, 0xc9, 0x27, 0x6c, 0x86, 0x11, 0xce, 0x05, 0x3e,
	0x11, 0xc8, 0xe7, 0xbe, 0x87, 0xed, 0x19, 0x67, 0x92, 0x91, 0x7d, 0x9f, 0xc9, 0xcb, 0x34, 0x76,
	0x69, 0x62, 0xf6, 0x01, 0x80, 0x83, 0xd2, 0xc5, 0x3f, 0x63, 0x14, 0x92, 0x10, 0xb8, 0x35, 0x61,
	0x42, 0x36, 0xd7, 0x0e, 0xd6, 0x8e, 0xb6, 0x5c, 0xfd, 0xdb, 0xe6, 0xd0, 0x72, 0x50, 0x9e, 0x84,
	0x21, 0x4a, 0xe4, 0x7d, 0x94, 0xd2, 0x8f, 0xc6, 0xc2, 0x45, 0x31, 0x63, 0x91, 0x40, 0xd2, 0x06,
	0xe2, 0xc5, 0x9c, 0x63, 0x24, 0xfb, 0x1e, 0x0d, 0xf0, 0x25, 0xf5, 0x24, 0xe3, 0xfa, 0xfb, 0x0d,
	0xb7, 0x24, 0x42, 0x0e, 0x61, 0xc7, 0x78, 0x7b, 0xa3, 0x91, 0x40, 0xd9, 0xb4, 0x74, 0x6a, 0xd1,
	0x69, 0x1f, 0x43, 0x53, 0x61, 0xc6, 0x72, 0xf2, 0x8a, 0x79, 0xd3, 0xbe, 0xa4, 0x12, 0x17, 0x88,
	0xf7, 0xe0, 0x76, 0xc0, 0xbc, 0x29, 0x0e, 0x35, 0xca, 0xa6, 0x6b, 0x2c, 0xfb, 0x02, 0xee, 0x39,
	0x28, 0x3b, 0x13, 0xca, 0xc7, 0xf8, 0xca, 0x0f, 0x7d, 0xb9, 0xf8, 0xe2, 0x3e, 0x6c, 0x85, 0x7e,
	0x10, 0xf8, 0x27, 0xe1, 0x4c, 0x98, 0xd6, 0x32, 0x07, 0x79, 0x08, 0xa0, 0x8d, 0x0b, 0x16, 0x48,
	0x61, 0xda, 0xc9, 0x79, 0xec, 0x5f, 0xe1, 0x6b, 0x55, 0x37, 0xe9, 0xaf, 0x43, 0x67, 0xd4, 0xf3,
	0xe5, 0xb5, 0x4b, 0xa3, 0x31, 0x9e, 0x45, 0xaa, 0xc0, 0x02, 0xa6, 0x09, 0x77, 0x42, 0x3f, 0xca,
	0x81, 0xa4, 0xa6, 0x8e, 0xd0, 0xbf, 0x74, 0xc4, 0x32, 0x91, 0xc4, 0xb4, 0x7b, 0xf0, 0xb9, 0x83,
	0xf2, 0x05, 0x06, 0xf4, 0x7a, 0xe0, 0x87, 0xc8, 0xf3, 0x3d, 0x0b, 0x49, 0xb9, 0x54, 0x5e, 0xb3,
	0x8e, 0xcc, 0xa1, 0x0a, 0x62, 0x34, 0xd4, 0x31, 0x4b, 0xc7, 0x52, 0xd3, 0x7e, 0xa7, 0xa7, 0x70,
	0x1a, 0x21, 0x1f, 0x5f, 0xbf, 0x16, 0x74, 0x9c, 0xcd, 0xed, 0x00, 0xb6, 0xaf, 0x26, 0x67, 0x51,
	0x1f, 0x85, 0xf0, 0x59, 0x64, 0x5a, 0xcc, 0xbb, 0xd4, 0x6e, 0xae, 0x26, 0x27, 0x9e, 0x17, 0x87,
	0x71, 0x40, 0x25, 0x0e, 0xd3, 0xdd, 0x14, 0x9c, 0xf6, 0x1b, 0xf8, 0x52, 0x21, 0xcc, 0x3b, 0x2c,
	0x8a, 0xd0, 0x93, 0xc5, 0xe5, 0x3c, 0x83, 0x0d, 0xa1, 0x1c, 0xba, 0x7c, 0xe3, 0xf8, 0xb0, 0x5d,
	0x76, 0x74, 0xed, 0xa5, 0x8f, 0x93, 0x4f, 0xec, 0x3f, 0xf4, 0xd2, 0x5f, 0xd2, 0x38, 0x90, 0x1d,
	0x16, 0x47, 0x12, 0x79, 0x36, 0x5b, 0x02, 0xb7, 0xc6, 0xa3, 0xa1, 0x6f, 0xba, 0xd6, 0xbf, 0x49,
	0x0b, 0x36, 0x23, 0xe6, 0x70, 0x16, 0x47, 0x69, 0xa7, 0x0b, 0x5b, 0x2d, 0x55, 0xc8, 0xd8, 0x9b,
	0xba, 0x6a, 0xb2, 0xcd, 0xf5, 0x64, 0xa9, 0x99, 0xc7, 0x3e, 0x87, 0x43, 0x07, 0x65, 0x6f, 0x8e,
	0x7c, 0x80, 0xe1, 0x0c, 0x39, 0x95, 0x31, 0xc7, 0xc1, 0x84, 0xa3, 0x98, 0xb0, 0x60, 0x58, 0xd8,
	0x29, 0x0d, 0xdf, 0xfb, 0x18, 0x25, 0x6f, 0xc2, 0x72, 0x53, 0x93, 0x34, 0xc0, 0xf2, 0xb9, 0xc6,
	0xb5, 0x5c, 0xcb, 0xe7, 0x76, 0x1b, 0x88, 0x7a, 0x48, 0xd2, 0x53, 0x6b, 0xc8, 0x7f, 0xcf, 0x13,
	0x97, 0x59, 0x62, 0x6a, 0xda, 0xa7, 0xf0, 0x99, 0x83, 0x72, 0xe5, 0x3d, 0x69, 0xc0, 0x19, 0x72,
	0x5c, 0x1c, 0x91, 0x31, 0xc9, 0x3e, 0x6c, 0x8c, 0x02, 0x3a, 0x56, 0x27, 0xb4, 0x7e, 0xb4, 0xe5,
	0x26, 0x86, 0xfd, 0x18, 0xf6, 0x1d, 0xd4, 0x47, 0x51, 0xbc, 0xf9, 0x7d, 0xd8, 0x08, 0x94, 0xc3,
	0x54, 0x49, 0x0c, 0x7b, 0xa2, 0x9b, 0xbc, 0x40, 0xae, 0xf6, 0xbd, 0xc8, 0x3d, 0x82, 0x4f, 0x47,
	0x3e, 0x0f, 0xaf, 0x28, 0x47, 0x13, 0x32, 0xcd, 0x2e, 0xbb, 0x55, 0xa6, 0x26, 0x13, 0x8f, 0x05,
	0x69, 0x66, 0x72, 0x7f, 0xcb, 0x6e, 0xfb, 0x02, 0xee, 0x2b, 0x24, 0x16, 0xc8, 0x72, 0xde, 0x78,
	0x08, 0xa0, 0x58, 0x61, 0x94, 0xe7, 0x8b, 0x9c, 0x47, 0xbd, 0x72, 0x96, 0x27, 0x08, 0x63, 0xd9,
	0x0f, 0x60, 0xbb, 0x8f, 0xd9, 0x9f, 0xd9, 0x00, 0x8b, 0x4d, 0x0d, 0x11, 0x58, 0x6c, 0x6a, 0x9f,
	0xc0, 0x5e, 0x3f, 0xb7, 0x85, 0x4a, 0x56, 0xcb, 0x2f, 0xc6, 0x2a, 0x2c, 0xe6, 0xd1, 0x4f, 0xd0,
	0x28, 0xde, 0x27, 0xd9, 0x83, 0x9d, 0x6e, 0x6f, 0x70, 0xd9, 0xe9, 0x75, 0xbb, 0xa7, 0x9d, 0xc1,
	0xe9, 0x8b, 0xdd, 0x4f, 0xc8, 0x0e, 0x6c, 0x65, 0xe6, 0x1a, 0xd9, 0x86, 0x3b, 0xaf, 0xbb, 0x3f,
	0x77, 0x7b, 0x6f, 0xba, 0xbb, 0xd6, 0xf1, 0xbf, 0x77, 0x61, 0xb3, 0x67, 0x4e, 0x9e, 0x24, 0x13,
	0x5f, 0x62, 0x4f, 0x72, 0x50, 0xfe, 0x2e, 0x32, 0x26, 0x6e, 0xfd, 0x50, 0x99, 0x51, 0xc5, 0xc4,
	0x43, 0xd8, 0x5d, 0xe6, 0xcc, 0x1a, 0x38, 0xed, 0x6a, 0x9c, 0x52, 0xf6, 0x7d, 0x07, 0x8d, 0x22,
	0xcb, 0xd6, 0xc0, 0x78, 0x5c, 0x99, 0x51, 0xc6, 0xd6, 0xff, 0xc0, 0x83, 0x0f, 0xf2, 0x6d, 0x0d,
	0xc0, 0x1f, 0xab, 0x01, 0x3f, 0x4e, 0xe3, 0xbf, 0xc3, 0x4e, 0x81, 0x92, 0x6b, 0xe0, 0x7d, 0x57,
	0x99, 0x51, 0xc2, 0xec, 0xc9, 0x04, 0x73, 0x0c, 0x7d, 0xa3, 0x09, 0x96, 0x31, 0xfd, 0x08, 0xf6,
	0x56, 0x18, 0xba, 0x06, 0xc8, 0xf7, 0xd5, 0x20, 0xe5, 0x64, 0x9f, 0x5c, 0x5c, 0x81, 0xb0, 0x6f,
	0x74, 0x71, 0xe5, 0xd4, 0xff, 0xb7, 0x66, 0x92, 0x4a, 0xaa, 0xae, 0x81, 0xf8, 0xac, 0x32, 0xe3,
	0xe3, 0x02, 0xf0, 0x36, 0xf9, 0xff, 0x28, 0xe1, 0x86, 0x1a, 0x58, 0x47, 0xd5, 0x19, 0x4b, 0xd2,
	0xf0, 0x0b, 0x6c, 0xe7, 0x04, 0xa0, 0x46, 0xe9, 0x6f, 0x2b, 0x33, 0x56, 0xb8, 0xe0, 0x37, 0xb8,
	0x9b, 0x57, 0x85, 0x1a, 0xc5, 0x1f, 0x55, 0x66, 0xac, 0x6a, 0x4b, 0x32, 0x93, 0x54, 0x13, 0x6e,
	0x32, 0x93, 0x65, 0x25, 0x0a, 0xb4, 0x9a, 0xad, 0xa8, 0x46, 0x0d, 0x8c, 0xe3, 0x6a, 0x8c, 0x4a,
	0x0d, 0x7a, 0x0b, 0x90, 0x89, 0x05, 0xf9, 0xa6, 0xbc, 0xc2, 0x8a, 0x9c, 0xb4, 0xbe, 0xaa, 0x4e,
	0x34, 0x95, 0x9f, 0x3f, 0x85, 0x2f, 0x3c, 0x16, 0xb6, 0xe9, 0x1c, 0xc7, 0x94, 0xa9, 0xf4, 0x76,
	0x9a, 0xfe, 0x7c, 0xf7, 0x8c, 0xc9, 0x54, 0x1d, 0xce, 0x95, 0x68, 0x9e, 0xaf, 0xfd, 0x67, 0xad,
	0xbb, 0x03, 0xe7, 0xfd, 0x6d, 0xad, 0xa1, 0x4f, 0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x70, 0xc7,
	0x32, 0x6c, 0xc5, 0x0b, 0x00, 0x00,
}
